twig:
    default_path: "%kernel.project_dir%/templates"
    form_themes:
        - "@FOSCKEditor/Form/ckeditor_widget.html.twig"
        - "@FOSCKEditor/Form/edit_widget.html.twig"
        - "@FOSCKEditor/Form/create_widget.html.twig"
    # fos_ck_editor:
    #     input_sync: true
